FROM ubuntu:24.04

RUN sed -i 's|http://archive.ubuntu.com|http://mirrors.aliyun.com|g' /etc/apt/sources.list.d/ubuntu.sources && \
    sed -i 's|http://security.ubuntu.com|http://mirrors.aliyun.com|g' /etc/apt/sources.list.d/ubuntu.sources && \
    cat /etc/apt/sources.list.d/ubuntu.sources && \
    apt-get update
# 安装基础依赖（可选）
RUN apt-get update && apt-get install -y build-essential clang-19 xmake git clangd-19 sudo unzip wget curl cmake lldb

# 设置环境变量

RUN useradd -m devcontainer
RUN usermod -aG sudo devcontainer
# 设置工作目录
WORKDIR /home/devcontainer/workspace/obelisk_coro
# 复制当前目录内容到容器中
COPY . /home/devcontainer/workspace/obelisk_coro

RUN CHOWN -R devcontainer:devcontainer /home/devcontainer/workspace

# 默认命令
CMD ["/bin/bash"]